pluginManagement {
    gradle.ext.kotlinVersion = '2.0.21'
    gradle.ext.kspVersion = '2.0.21-1.0.28'
    gradle.ext.agpVersion = '8.12.0'
    gradle.ext.automatticPublishToS3Version = '0.8.0'
    gradle.ext.dependencyAnalysisVersion = '1.33.0'

    plugins {
        id 'com.android.library' version gradle.ext.agpVersion
        id 'com.android.application' version gradle.ext.agpVersion
        id 'org.jetbrains.kotlin.android' version gradle.ext.kotlinVersion
        id 'com.automattic.android.publish-to-s3' version gradle.ext.automatticPublishToS3Version
        id 'androidx.benchmark' version '1.2.4'
        id "com.autonomousapps.dependency-analysis" version gradle.ext.dependencyAnalysisVersion
        id 'com.google.devtools.ksp' version gradle.ext.kspVersion
        id 'org.jetbrains.kotlinx.binary-compatibility-validator' version '0.16.3'
    }
    repositories {
        maven {
            url 'https://a8c-libs.s3.amazonaws.com/android' 
            content {
                includeGroup 'com.automattic.android'
                includeGroup 'com.automattic.android.publish-to-s3'
            }
        }
        google()
        gradlePluginPortal()
    }
}

include ':AutomatticTracks'
include ':sampletracksapp'
include ':experimentation'
include ':crashlogging'
include ':benchmark'
