orbs:
  android: wordpress-mobile/android@1.0

version: 2.1
jobs:
  Build:
    executor:
      name: android/default
      api-version: "30"
    steps:
      - checkout
      - android/restore-gradle-cache
      - run:
          name: Setup gradle.properties
          command: cp gradle.properties-example gradle.properties
      - run:
          name: Static code analysis
          command: ./gradlew --stacktrace ktlint
      - run:
          name: Assemble .aar
          command: ./gradlew --stacktrace assembleRelease
      - run:
          name: Run unit tests
          command: ./gradlew --stacktrace testRelease
      - run:
          name: Run Android lint
          command: ./gradlew --stacktrace lintRelease
      - run:
          name: Assert build correctness on Jitpack
          command: ./gradlew --stacktrace publishToMavenLocal
      - android/save-gradle-cache
      - android/save-test-results

workflows:
  tracks-android:
    jobs:
      - Build

