common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.11.0

steps:
  - label: "Lint"
    key: "lint"
    plugins: *common_plugins
    command: |
      cp gradle.properties-example gradle.properties
      ./gradlew lintRelease ciktlint
    artifact_paths:
      - "**/build/reports/lint-results.*"
      - "**/build/ktlint.xml"

  - label: "Test"
    key: "test"
    plugins: *common_plugins
    command: |
      cp gradle.properties-example gradle.properties
      ./gradlew test

  - label: "Publish {{matrix}} to S3"
    depends_on:
      - "lint"
      - "test"
    plugins: *common_plugins
    matrix:
      - AutomatticTracks
      - experimentation
    command: |
      cp gradle.properties-example gradle.properties
      ./gradlew \
          :{{matrix}}:prepareToPublishToS3 $(prepare_to_publish_to_s3_params) \
          :{{matrix}}:publish
